apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: socialecho-ingress-canary
  namespace: socialecho
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /server-status
    alb.ingress.kubernetes.io/canary: "true"
    alb.ingress.kubernetes.io/canary-weight: "10"
    alb.ingress.kubernetes.io/canary-by-ingress: "socialecho-ingress-stable"
spec:
  ingressClassName: alb
  rules:
    - host: k8s-socialec-socialec-c956ab9939-933116048.ap-south-1.elb.amazonaws.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-canary
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-canary
                port:
                  number: 80
